name: Build and Deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'  
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Update Browserslist
        run: npm run update-browserslist

      - name: Build the project
        run: npm run build

      - name: Check build directory
        run: ls -R ./build 

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: cafeshop3  
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}  
          package: build  
